// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHgWkf9JIsWQ0nhxEfcJ1Je5PfrcugO4M',
    appId: '1:883042754761:web:e9497bbc7ed981c866ed18',
    messagingSenderId: '883042754761',
    projectId: 'laihan01',
    authDomain: 'laihan01.firebaseapp.com',
    storageBucket: 'laihan01.firebasestorage.app',
    measurementId: 'G-076VK5KLPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7NYJ_OU6VU9xj89G1nmRKpVpxhQ3jzrI',
    appId: '1:883042754761:android:22f5fca240e0293566ed18',
    messagingSenderId: '883042754761',
    projectId: 'laihan01',
    storageBucket: 'laihan01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfil2dO17_nnmCUCcv65J8S6Z2xQAEzPE',
    appId: '1:883042754761:ios:0b752b423e4b062c66ed18',
    messagingSenderId: '883042754761',
    projectId: 'laihan01',
    storageBucket: 'laihan01.firebasestorage.app',
    iosBundleId: 'com.example.laihan01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfil2dO17_nnmCUCcv65J8S6Z2xQAEzPE',
    appId: '1:883042754761:ios:0b752b423e4b062c66ed18',
    messagingSenderId: '883042754761',
    projectId: 'laihan01',
    storageBucket: 'laihan01.firebasestorage.app',
    iosBundleId: 'com.example.laihan01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHgWkf9JIsWQ0nhxEfcJ1Je5PfrcugO4M',
    appId: '1:883042754761:web:fd0b74dd8c1bca2266ed18',
    messagingSenderId: '883042754761',
    projectId: 'laihan01',
    authDomain: 'laihan01.firebaseapp.com',
    storageBucket: 'laihan01.firebasestorage.app',
    measurementId: 'G-8HLVLZBRBM',
  );
}